### ISSUE TITLE
How to create a new user "alice" on K8s (RBAC)

### ISSUE THREAD

**Issue by juan131** [spiddy/kubernetes-security-workshop#2]
How to create a Certificate for an user (using OpenSSL):

```
$ openssl req -new -key /path/to/your/keys/alice.key -out /tmp/alice.csr -subj "/CN=alice/O=devs/O=tech-lead"
````

As you can check you're creating a certificate sign request for user **"alice"** that belongs to groups **"devs"** and **"tech-lead"**

Then you need to sign it with the Certificate Authority:

```
$ openssl x509 -req -in /tmp/alice.csr -CA /path/to/ca/keys/ca.crt -CAkey  /path/to/ca/keys/ca.key -CAcreateserial -out /path/to/your/keys/alice.crt  -days 500 
```

Finally configure kubectl to use the certificate:

```
$ kubectl config set-credentials alice@YOU_CLUSTER_IP --client-certificate="/path/to/your/keys/alice.crt" --client-key="/path/to/your/keys/alice.key" --embed-certs=true
```

**Comment by juan131** [comment]
Two important fields in the SSL certificate:
- Common Name (CN): Kubernetes will interpret this value as the **user**
- Organization (O): Kubernetes will interpret this value as the **group**

**Comment by dkapanidis** [comment]
Added examples on RBAC about using User and generating credentials, thnks!
